# Generated by Django 2.1.7 on 2019-03-10 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
