# Generated by Django 2.1.7 on 2019-03-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InsCompany', '0002_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tco_tcc_id', models.IntegerField(default=0)),
                ('tco_tpr_id', models.IntegerField(default=0)),
                ('tco_tcs_id', models.IntegerField(default=0)),
                ('tco_tfp_id', models.IntegerField(default=0)),
                ('tco_number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('tco_start_date', models.DateTimeField(auto_now=True)),
                ('tco_pre_end_date', models.DateTimeField(auto_now=True)),
                ('tco_end_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
