# Generated by Django 2.1.7 on 2019-04-06 09:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0003_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpr_name', models.CharField(max_length=255)),
                ('tpr_born_date', models.DateTimeField(default=datetime.datetime(2019, 4, 6, 12, 32, 1, 121951))),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='tco_tpr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.Person'),
        ),
    ]
