# Generated by Django 2.1.7 on 2019-04-06 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0004_auto_20190406_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='tpr_born_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 6, 13, 11, 57, 263879)),
        ),
    ]
