# Generated by Django 2.1.7 on 2019-04-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0005_auto_20190406_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='tpr_born_date',
            field=models.DateTimeField(),
        ),
    ]
