# Generated by Django 2.1.7 on 2019-04-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0008_auto_20190406_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='tco_tpr_id',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
