# Generated by Django 2.1.7 on 2019-04-06 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0009_auto_20190406_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpr_surname', models.CharField(max_length=80)),
                ('tpr_forename', models.CharField(max_length=80)),
                ('tpr_middle', models.CharField(max_length=80)),
                ('tpr_born_date', models.DateField()),
                ('tpr_main_doc', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='tco_tpr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.Person'),
        ),
    ]
