# Generated by Django 2.1.7 on 2019-04-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0011_addresstype_claimstatus_contacttype_contractseries_contractstatus_documenttype_freqpay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContractSeries',
        ),
    ]
