# Generated by Django 2.1.7 on 2019-04-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0012_delete_contractseries'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcss_val', models.CharField(max_length=50)),
            ],
        ),
    ]
