# Generated by Django 2.1.7 on 2019-04-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0013_contractseries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='tco_tpr_id',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
