# Generated by Django 2.1.7 on 2019-04-06 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0014_auto_20190406_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tco_number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('tco_start_date', models.DateTimeField(auto_now=True)),
                ('tco_pre_end_date', models.DateTimeField(auto_now=True)),
                ('tco_end_date', models.DateTimeField(auto_now=True)),
                ('tco_tcs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.ContractStatus')),
                ('tco_tcss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.ContractSeries')),
                ('tco_tfp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.FreqPay')),
                ('tco_tpr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.Person')),
            ],
        ),
    ]
