# Generated by Django 2.1.7 on 2019-04-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0015_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='tco_length',
            field=models.IntegerField(default=1),
        ),
    ]
