# Generated by Django 2.1.7 on 2019-04-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0016_contract_tco_length'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClaimStatus',
        ),
        migrations.AlterField(
            model_name='contract',
            name='tco_tcs_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tco_tcss_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tco_tfp_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tco_tpr_id',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='ContractSeries',
        ),
        migrations.DeleteModel(
            name='ContractStatus',
        ),
        migrations.DeleteModel(
            name='FreqPay',
        ),
    ]
