# Generated by Django 2.1.7 on 2019-04-06 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0017_auto_20190406_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcs_val', models.CharField(max_length=50)),
                ('tcs_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContractSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcss_val', models.CharField(max_length=50)),
                ('tcss_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContractStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcs_val', models.CharField(max_length=50)),
                ('tcs_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FreqPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tfp_val', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='tco_tcs_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.ContractStatus'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tco_tcss_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.ContractSeries'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tco_tfp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.FreqPay'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tco_tpr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.Person'),
        ),
    ]
