# Generated by Django 2.1.7 on 2019-04-06 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0018_auto_20190406_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='tco_tcs_id',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='InsCompany.ContractStatus'),
        ),
    ]
