# Generated by Django 2.1.7 on 2019-04-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0019_auto_20190406_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tpr_psycho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='tpr_unprofit',
            field=models.BooleanField(default=False),
        ),
    ]
