# Generated by Django 2.1.7 on 2019-04-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0020_auto_20190406_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='tpr_psycho',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='tpr_unprofit',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
