# Generated by Django 2.1.7 on 2019-04-06 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0021_auto_20190406_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr_val', models.CharField(max_length=300)),
                ('addr_tat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.AddressType')),
                ('addr_tpr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_val', models.CharField(max_length=40)),
                ('con_tct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.ContactType')),
                ('con_tpr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tde_number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('tde_start', models.DateField()),
                ('tde_end', models.DateField()),
                ('tde_tpr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_series', models.CharField(max_length=30)),
                ('doc_number', models.CharField(max_length=30)),
                ('doc_issue_date', models.DateField()),
                ('doc_issue_org', models.CharField(max_length=255)),
                ('doc_tdt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.DocumentType')),
                ('doc_tpr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.Person')),
            ],
        ),
    ]
