# Generated by Django 2.1.7 on 2019-04-06 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0022_address_contact_dealer_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcd_start', models.DateField()),
                ('tcd_end', models.DateField()),
                ('tcd_tco_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.Contract')),
                ('tcd_tde_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.Dealer')),
            ],
        ),
        migrations.CreateModel(
            name='ContractRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcr_sum', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tcr_start', models.DateField()),
                ('tcr_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ElemClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_sum', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tel_sum_fact', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='InsEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiv_date', models.DateField()),
                ('tiv_time', models.TimeField()),
                ('tiv_tco_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.Contact')),
                ('tiv_tcs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.ClaimStatus')),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpo_date', models.DateField()),
                ('tpo_sum', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tpo_tel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.ElemClaim')),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsk_name', models.CharField(max_length=50)),
                ('rsk_tcss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.ContractSeries')),
            ],
        ),
        migrations.CreateModel(
            name='TerrList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttl_surname', models.CharField(max_length=80)),
                ('ttl_forename', models.CharField(max_length=80)),
                ('ttl_middle', models.CharField(max_length=80)),
                ('ttl_born_date', models.DateField()),
                ('tpr_main_doc', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='elemclaim',
            name='tel_rsk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.Risk'),
        ),
        migrations.AddField(
            model_name='elemclaim',
            name='tel_tcs_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.ClaimStatus'),
        ),
        migrations.AddField(
            model_name='elemclaim',
            name='tel_tiv_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.InsEvent'),
        ),
        migrations.AddField(
            model_name='contractrisk',
            name='tcr_rsk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.Risk'),
        ),
        migrations.AddField(
            model_name='contractrisk',
            name='tcr_tco_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.Contract'),
        ),
    ]
