# Generated by Django 2.1.7 on 2019-04-10 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0023_auto_20190406_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='tco_tcss_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InsCompany.ContractSeries'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tco_tfp_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InsCompany.FreqPay'),
        ),
    ]
