# Generated by Django 2.1.7 on 2019-05-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0024_auto_20190411_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='rsk_proportion',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contractrisk',
            name='tcr_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contractrisk',
            name='tcr_start',
            field=models.DateField(null=True),
        ),
    ]
