# Generated by Django 2.1.7 on 2019-05-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0025_auto_20190502_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='rsk_ins_proportion',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
