# Generated by Django 2.1.7 on 2019-05-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0027_auto_20190502_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='insevent',
            name='tiv_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='tpo_commentary',
            field=models.TextField(null=True),
        ),
    ]
