# Generated by Django 2.1.7 on 2019-05-02 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0028_auto_20190503_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insevent',
            name='tiv_tco_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.Contract'),
        ),
    ]
