# Generated by Django 2.1.7 on 2019-05-05 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InsCompany', '0029_auto_20190503_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_photo', models.ImageField(upload_to='MyGW/InsCompany/static/images')),
                ('wp_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
