# Generated by Django 2.1.7 on 2019-05-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0031_auto_20190509_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='tco_app_original',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
