# Generated by Django 2.1.7 on 2019-05-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0032_contract_tco_app_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='tco_app_original',
            field=models.FileField(null=True, upload_to='MyGW/InsCompany/media/docs/'),
        ),
    ]
