# Generated by Django 2.1.7 on 2019-05-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0033_auto_20190509_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='tco_app_original',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
