# Generated by Django 2.1.7 on 2019-05-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0035_dealer_tde_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdealer',
            name='tcd_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contractdealer',
            name='tcd_start',
            field=models.DateField(null=True),
        ),
    ]
