# Generated by Django 2.1.7 on 2019-05-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0036_auto_20190510_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='tco_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tco_pre_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tco_start_date',
            field=models.DateField(null=True),
        ),
    ]
