# Generated by Django 2.1.7 on 2019-05-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0038_auto_20190511_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerphoto',
            name='wp_photo',
            field=models.ImageField(upload_to='worker_photo/'),
        ),
    ]
