# Generated by Django 2.1.7 on 2019-05-11 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0039_auto_20190511_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='tpo_tel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsCompany.InsEvent'),
        ),
        migrations.AlterField(
            model_name='workerphoto',
            name='wp_photo',
            field=models.ImageField(upload_to='worker_photos/'),
        ),
    ]
