# Generated by Django 2.1.7 on 2019-05-12 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0040_auto_20190512_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractstatus',
            name='tcs_desc',
        ),
    ]
