# Generated by Django 2.1.7 on 2019-05-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0044_auto_20190512_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemclaim',
            name='tel_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='elemclaim',
            name='tel_sum_fact',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
