# Generated by Django 2.1.7 on 2019-05-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0045_auto_20190512_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='insevent',
            name='tiv_app_date',
            field=models.DateField(default='2019-02-02'),
        ),
        migrations.AlterField(
            model_name='insevent',
            name='tiv_desc',
            field=models.TextField(default='пидр'),
        ),
    ]
