# Generated by Django 2.1.7 on 2019-05-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0046_auto_20190512_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insevent',
            name='tiv_app_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='insevent',
            name='tiv_desc',
            field=models.TextField(),
        ),
    ]
