# Generated by Django 2.1.7 on 2019-05-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0047_auto_20190512_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payout',
            old_name='tpo_tel_id',
            new_name='tpo_tiv_id',
        ),
    ]
