# Generated by Django 2.1.7 on 2019-05-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0048_auto_20190512_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='tpo_date',
            field=models.DateField(null=True),
        ),
    ]
