# Generated by Django 2.1.7 on 2019-05-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0049_auto_20190512_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrisk',
            name='tcr_str_sum',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=20),
            preserve_default=False,
        ),
    ]
