# Generated by Django 2.1.7 on 2019-05-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsCompany', '0051_auto_20190513_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='rsk_ins_proportion',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
